### PR TITLE
WIP: Use @grafana/toolkit

### PR DESCRIPTION
**Pull request by ryantxu**
NOTE: this is work in progress

I'm trying to get a single build system to build and test most plugins.  If we merge your fork into the main plugin, it would be great to have it working also.

The main changes are:
* removing dist from the `master` repo
* more consistent code styles/linting

I have not yet looks at any of the substantive changes to this fork, but that will be next :)

### CODE REVIEW

**Comment by amotl** [comment]
Dear Ryan,

thank you so much for also taking care about our work here.

> I'm trying to get a single build system to build and test most plugins.

Sounds like a good plan!

> If we merge your fork into the main plugin, it would be great to have it working also.

We are happy to see that you are able to dedicate some time to Worldmap and might also become the one we would dearly need to work on the actual upstreaming. Please let us know if this resonates with you, we will try to follow any advice you might give us for this journey.

As you are much more involved into the innards of Grafana and the upcoming transitions under the hood, we will just add you as a member to this repository so that it will be at your disposal to use it as a kind of staging area and to remove the obstacle to go through pull requests. ¹

In this way, anyone interested in building a dist package from these sources we will be able to deploy it side-by-side to the vanilla Worldmap Panel as we renamed it slightly to `grafana-worldmap-panel-ng`. 

As soon as we and maybe a few others might be able to confirm everything still works in their scenarios (e.g. looking at Worldping here), we might think about bringing it back to mainline. At least, these are the thoughts we've had about that topic. Let us know if this qualifies as a plan already ;].

Thanks again and with kind regards,
Andreas.

¹ We hope you appreciate that, feel free to amend things right there if you like. Please recognize that we've set the default branch of this repository to "develop".

**Comment by ryantxu** [comment]
>  we will just add you as a member to this repository

Thanks -- that will make things easier

I have pushed a few changes, but am not really using this panel so will need help testing to make sure they actually work :)

Also, can you enable circle integration?  after I am a member, I may be able to set it up for this repository too.  With circle, we can get a .zip for every commit and PR

**Comment by amotl** [comment]
> Thanks -- that will make things easier

Good thing ;].

> I have pushed a few changes, but am not really using this panel so will need help testing to make sure they actually work :)

We will be happy to check that on an appropriate Grafana instance we are using for that. Just asking: Will this drop support for Grafana 5 or should it still work on it?

> Also, can you enable circle integration? after I am a member, I may be able to set it up for this repository too.

We added you as "Maintainer", this is slightly elevated above just having "Write" permissions. As we've never worked with CircleCI yet, we will be happy if you could add this.

> With circle, we can get a .zip for every commit and PR.

Sounds good. Thanks.

**Comment by amotl** [comment]
> Can you enable circle integration?

I just navigated to [1] which yelled at me that GitHub Services have been deprecated ;[. Now, I'm feeling a bit lost.

[1] https://github.com/hiveeyes/grafana-worldmap-panel/settings/installations

**Comment by ryantxu** [comment]
> Just asking: Will this drop support for Grafana5 or should it still work on it?

The changes to the build should not (yet) change how and where the plugin is supported.  

Before merging into the main repository, there may be some changes that would require this to run on a more recent (likely 6.3) grafana build.

**Comment by ryantxu** [comment]
I moved the work to integrate @grafana/toolkit to: https://github.com/hiveeyes/grafana-worldmap-panel/tree/with-toolkit

**Pull request closed without merging**
